# Generated by Django 5.0.6 on 2026-07-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name (नाम)')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number (नंबर)')),
                ('designation', models.CharField(max_length=255, verbose_name='अधिकारी पद')),
                ('city', models.CharField(max_length=100, verbose_name='City (शहर)')),
                ('state', models.CharField(max_length=100, verbose_name='State (राज्य)')),
                ('address', models.TextField(verbose_name='Address (पत्ता)')),
                ('work', models.TextField(verbose_name='Work (काम)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='officers_of_name_5df6fd_idx'), models.Index(fields=['mobile_number'], name='officers_of_mobile__0c0aa3_idx'), models.Index(fields=['city'], name='officers_of_city_195086_idx'), models.Index(fields=['state'], name='officers_of_state_4d6bd3_idx'), models.Index(fields=['designation'], name='officers_of_designa_56d29f_idx')],
            },
        ),
    ]
