# Generated by Django 5.0.6 on 2026-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='division',
            field=models.CharField(blank=True, choices=[('education', 'Education (शिक्षा)'), ('health', 'Health (आरोग्य)'), ('transport', 'Transport (वाहतूक)'), ('security', 'Security (सुरक्षा)'), ('sanitation', 'Sanitation (स्वच्छता)'), ('district_office', 'District Office (जिल्हाधिकारी कार्यालय)'), ('divisional_commissioner', 'Divisional Commissioner Office (विभागीय आयुक्त कार्यालय)'), ('kumbh_authority', 'Kumbh Mela Authority'), ('police', 'Police (पोलीस)'), ('other', 'Other')], max_length=50, null=True, verbose_name='Division (विभाग)'),
        ),
        migrations.AddField(
            model_name='officer',
            name='government_level',
            field=models.CharField(blank=True, choices=[('central', 'Central Govt'), ('state', 'State Govt')], max_length=20, null=True, verbose_name='Govt Level'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['division'], name='officers_of_divisio_da4e72_idx'),
        ),
    ]
