# Generated by Django 5.0.6 on 2026-07-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_officer_division_officer_government_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='officer',
            name='contact_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact 2'),
        ),
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department (विभाग)'),
        ),
        migrations.AddField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='officer',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Office Phone'),
        ),
        migrations.AddField(
            model_name='officer',
            name='pbx_extension',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PBX Extension'),
        ),
        migrations.AddField(
            model_name='officer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='officer_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='officer',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Category'),
        ),
    ]
