# Generated by Django 5.0.6 on 2026-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_officer_category_officer_contact_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='main_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Main Type'),
        ),
        migrations.AddField(
            model_name='officer',
            name='sub_sub_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub-Sub Type'),
        ),
        migrations.AddField(
            model_name='officer',
            name='sub_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub Type'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category (जात)'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Department (शाखा)'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Category (पोटजात)'),
        ),
    ]
