# Generated by Django 5.0.6 on 2026-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_officer_main_type_officer_sub_sub_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='contact_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact 2'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name='Mobile Number (नंबर)'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='office_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Office Phone'),
        ),
    ]
